//! OpenAPI 文档装配。

#[cfg(all(debug_assertions, feature = "openapi"))]
use utoipa::openapi::security::{ApiKey, ApiKeyValue, Http, HttpAuthScheme, SecurityScheme};
#[cfg(all(debug_assertions, feature = "openapi"))]
use utoipa::{Modify, OpenApi};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "AsterDrive API",
        version = env!("CARGO_PKG_VERSION"),
        description = "Self-hosted cloud storage API",
        license(name = "MIT"),
    ),
    modifiers(&SecurityAddon),
    paths(
        // auth::public：无需登录即可访问的安装检查、初始化、注册验证与密码找回接口。
        crate::api::routes::auth::public::check,
        crate::api::routes::auth::public::setup,
        crate::api::routes::auth::public::register,
        crate::api::routes::auth::public::resend_register_activation,
        crate::api::routes::auth::public::verify_user_invitation,
        crate::api::routes::auth::public::accept_user_invitation,
        crate::api::routes::auth::public::confirm_contact_verification,
        crate::api::routes::auth::public::request_password_reset,
        crate::api::routes::auth::public::confirm_password_reset,

        // auth::session：负责登录态建立、续期、退出以及当前会话信息查询。
        crate::api::routes::auth::session::login,
        crate::api::routes::auth::session::refresh,
        crate::api::routes::auth::session::logout,
        crate::api::routes::auth::session::me,
        crate::api::routes::auth::session::list_sessions,
        crate::api::routes::auth::session::delete_other_sessions,
        crate::api::routes::auth::session::delete_session,
        crate::api::routes::auth::session::put_password,
        crate::api::routes::auth::passkeys::list_passkeys,
        crate::api::routes::auth::passkeys::start_registration,
        crate::api::routes::auth::passkeys::finish_registration,
        crate::api::routes::auth::passkeys::rename_passkey,
        crate::api::routes::auth::passkeys::delete_passkey,
        crate::api::routes::auth::passkeys::start_login,
        crate::api::routes::auth::passkeys::finish_login,
        crate::api::routes::auth::external_auth::list_providers,
        crate::api::routes::auth::external_auth::start_login,
        crate::api::routes::auth::external_auth::finish_login,
        crate::api::routes::auth::external_auth::start_email_verification,
        crate::api::routes::auth::external_auth::link_with_password,
        crate::api::routes::auth::external_auth::confirm_email_verification,
        crate::api::routes::auth::external_auth::list_links,
        crate::api::routes::auth::external_auth::delete_link,
        crate::api::routes::auth::mfa::verify_challenge,
        crate::api::routes::auth::mfa::send_email_code,
        crate::api::routes::auth::mfa::status,
        crate::api::routes::auth::mfa::start_totp_setup,
        crate::api::routes::auth::mfa::finish_totp_setup,
        crate::api::routes::auth::mfa::delete_factor,
        crate::api::routes::auth::mfa::regenerate_recovery_codes,

        // auth::profile：已登录用户的资料、头像和偏好设置维护接口。
        crate::api::routes::auth::profile::request_email_change,
        crate::api::routes::auth::profile::resend_email_change,
        crate::api::routes::auth::profile::patch_preferences,
        crate::api::routes::auth::profile::patch_profile,
        crate::api::routes::auth::profile::upload_avatar,
        crate::api::routes::auth::profile::put_avatar_source,
        crate::api::routes::auth::profile::get_self_avatar,

        // health：用于存活探针和就绪探针，给网关和运维检查服务状态。
        crate::api::routes::health::health,
        crate::api::routes::health::primary_ready,

        // public：登录前也能读取的公开站点配置，例如品牌信息和预览应用列表。
        crate::api::routes::public::get_frontend_config,
        crate::api::routes::public::get_preview_apps,
        crate::api::routes::public::get_thumbnail_support,
        crate::api::routes::public::get_media_data_support,
        crate::api::routes::public::redeem_remote_enrollment,
        crate::api::routes::public::ack_remote_enrollment,

        // files::upload：个人空间文件上传生命周期，包括直传、分片和进度控制。
        crate::api::routes::files::upload::upload,
        crate::api::routes::files::upload::init_chunked_upload,
        crate::api::routes::files::upload::upload_chunk,
        crate::api::routes::files::upload::complete_upload,
        crate::api::routes::files::upload::presign_parts,
        crate::api::routes::files::upload::list_recoverable_upload_sessions,
        crate::api::routes::files::upload::get_upload_progress,
        crate::api::routes::files::upload::cancel_upload,

        // files::access：个人空间中文件读取、下载、缩略图、直链和 WOPI 打开入口。
        crate::api::routes::files::access::get_file,
        crate::api::routes::files::access::get_archive_preview,
        crate::api::routes::files::access::get_direct_link,
        crate::api::routes::files::access::get_preview_link,
        crate::api::routes::files::access::open_wopi,
        crate::api::routes::files::access::download,
        crate::api::routes::files::access::get_thumbnail,
        crate::api::routes::files::access::get_image_preview,
        crate::api::routes::files::access::get_media_metadata,

        // files::mutations：个人文件的创建、重命名、内容更新、解压、复制和删除操作。
        crate::api::routes::files::mutations::create_empty,
        crate::api::routes::files::mutations::delete_file,
        crate::api::routes::files::mutations::patch_file,
        crate::api::routes::files::mutations::update_content,
        crate::api::routes::files::mutations::extract_archive,
        crate::api::routes::files::mutations::set_lock,
        crate::api::routes::files::mutations::copy_file,

        // files::versions：个人文件历史版本的查询、恢复与删除。
        crate::api::routes::files::versions::list_versions,
        crate::api::routes::files::versions::restore_version,
        crate::api::routes::files::versions::delete_version,

        // folders：个人目录树的浏览、创建、重命名、复制、锁定与删除操作。
        crate::api::routes::folders::list_root,
        crate::api::routes::folders::create_folder,
        crate::api::routes::folders::list_folder,
        crate::api::routes::folders::get_folder_info,
        crate::api::routes::folders::get_ancestors,
        crate::api::routes::folders::delete_folder,
        crate::api::routes::folders::patch_folder,
        crate::api::routes::folders::set_lock,
        crate::api::routes::folders::copy_folder,

        // search：个人空间内的文件与文件夹检索接口。
        crate::api::routes::search::search,

        // tags：个人空间标签定义、绑定和实体标签读取入口。
        crate::api::routes::tags::list_tags,
        crate::api::routes::tags::create_tag,
        crate::api::routes::tags::patch_tag,
        crate::api::routes::tags::delete_tag,

        // batch：个人空间内的批量删除、移动、复制和归档下载操作。
        crate::api::routes::batch::batch_delete,
        crate::api::routes::batch::batch_move,
        crate::api::routes::batch::batch_copy,
        crate::api::routes::batch::archive_compress,
        crate::api::routes::batch::archive_download,
        crate::api::routes::batch::archive_download_stream,

        // shares：登录用户创建和维护个人文件/文件夹分享的接口。
        crate::api::routes::shares::create_share,
        crate::api::routes::shares::list_shares,
        crate::api::routes::shares::update_share,
        crate::api::routes::shares::delete_share,
        crate::api::routes::shares::batch_delete_shares,

        // tasks：用户可见的后台任务查询与重试入口。
        crate::api::routes::tasks::list_tasks,
        crate::api::routes::tasks::get_task,
        crate::api::routes::tasks::retry_task,
        crate::api::routes::tasks::create_offline_download,

        // trash：个人回收站内容浏览、恢复和清空操作。
        crate::api::routes::trash::list_trash,
        crate::api::routes::trash::restore,
        crate::api::routes::trash::purge_one,
        crate::api::routes::trash::purge_all,

        // teams：团队本身的创建、设置变更、成员管理与审计日志查询。
        crate::api::routes::teams::list_teams,
        crate::api::routes::teams::create_team,
        crate::api::routes::teams::get_team,
        crate::api::routes::teams::patch_team,
        crate::api::routes::teams::delete_team,
        crate::api::routes::teams::restore_team,
        crate::api::routes::teams::list_audit_logs,
        crate::api::routes::teams::list_members,
        crate::api::routes::teams::add_member,
        crate::api::routes::teams::patch_member,
        crate::api::routes::teams::delete_member,

        // shares：团队空间下的分享创建、更新和批量移除。
        crate::api::routes::shares::team_create_share,
        crate::api::routes::shares::team_list_shares,
        crate::api::routes::shares::team_update_share,
        crate::api::routes::shares::team_delete_share,
        crate::api::routes::shares::team_batch_delete_shares,

        // tasks：团队空间后台任务的查询和重试。
        crate::api::routes::tasks::team_list_tasks,
        crate::api::routes::tasks::team_get_task,
        crate::api::routes::tasks::team_retry_task,
        crate::api::routes::tasks::team_create_offline_download,

        // batch：团队空间内的批量删除、移动、复制与归档下载。
        crate::api::routes::batch::team_batch_delete,
        crate::api::routes::batch::team_batch_move,
        crate::api::routes::batch::team_batch_copy,
        crate::api::routes::batch::team_archive_compress,
        crate::api::routes::batch::team_archive_download,
        crate::api::routes::batch::team_archive_download_stream,

        // search：团队空间内的文件与文件夹搜索。
        crate::api::routes::search::team_search,

        // tags：团队空间标签定义与绑定入口。
        crate::api::routes::tags::team_list_tags,
        crate::api::routes::tags::team_create_tag,
        crate::api::routes::tags::team_patch_tag,
        crate::api::routes::tags::team_delete_tag,

        // folders：团队目录树的浏览、创建、重命名、复制、锁定与删除。
        crate::api::routes::folders::team_list_root,
        crate::api::routes::folders::team_create_folder,
        crate::api::routes::folders::team_list_folder,
        crate::api::routes::folders::team_get_folder_info,
        crate::api::routes::folders::team_get_ancestors,
        crate::api::routes::folders::team_patch_folder,
        crate::api::routes::folders::team_delete_folder,
        crate::api::routes::folders::team_set_lock,
        crate::api::routes::folders::team_copy_folder,

        // files：团队文件的上传、下载、预览、版本和变更操作。
        crate::api::routes::files::upload::team_upload,
        crate::api::routes::files::upload::team_init_chunked_upload,
        crate::api::routes::files::upload::team_upload_chunk,
        crate::api::routes::files::upload::team_complete_upload,
        crate::api::routes::files::upload::team_presign_parts,
        crate::api::routes::files::upload::team_list_recoverable_upload_sessions,
        crate::api::routes::files::upload::team_get_upload_progress,
        crate::api::routes::files::upload::team_cancel_upload,
        crate::api::routes::files::mutations::team_create_empty,
        crate::api::routes::files::access::team_get_file,
        crate::api::routes::files::access::team_get_archive_preview,
        crate::api::routes::files::access::team_get_direct_link,
        crate::api::routes::files::access::team_get_preview_link,
        crate::api::routes::files::access::team_open_wopi,
        crate::api::routes::files::access::team_get_thumbnail,
        crate::api::routes::files::access::team_get_image_preview,
        crate::api::routes::files::access::team_get_media_metadata,
        crate::api::routes::files::mutations::team_update_content,
        crate::api::routes::files::mutations::team_extract_archive,
        crate::api::routes::files::mutations::team_set_lock,
        crate::api::routes::files::mutations::team_patch_file,
        crate::api::routes::files::mutations::team_copy_file,
        crate::api::routes::files::versions::team_list_versions,
        crate::api::routes::files::versions::team_restore_version,
        crate::api::routes::files::versions::team_delete_version,
        crate::api::routes::files::access::team_download,
        crate::api::routes::files::mutations::team_delete_file,

        // trash：团队回收站的浏览、恢复和永久清理操作。
        crate::api::routes::trash::team_list_trash,
        crate::api::routes::trash::team_restore,
        crate::api::routes::trash::team_purge_one,
        crate::api::routes::trash::team_purge_all,

        // webdav_accounts：用户 WebDAV 账户的创建、启停、配置查看与连通性测试。
        crate::api::routes::webdav_accounts::list_accounts,
        crate::api::routes::webdav_accounts::get_settings,
        crate::api::routes::webdav_accounts::create_account,
        crate::api::routes::webdav_accounts::delete_account,
        crate::api::routes::webdav_accounts::toggle_account,
        crate::api::routes::webdav_accounts::list_team_accounts,
        crate::api::routes::webdav_accounts::create_team_account,
        crate::api::routes::webdav_accounts::delete_team_account,
        crate::api::routes::webdav_accounts::toggle_team_account,
        crate::api::routes::webdav_accounts::test_connection,

        // properties：实体级自定义属性的读取、写入与删除。
        crate::api::routes::properties::list_props,
        crate::api::routes::properties::set_prop,
        crate::api::routes::properties::delete_prop,

        // admin::overview：后台首页总览数据。
        crate::api::routes::admin::overview::get_overview,
        crate::api::routes::admin::system_info::get_system_info,

        // admin::policies：存储策略、策略组及其验证相关接口。
        crate::api::routes::admin::policies::list_policies,
        crate::api::routes::admin::policies::list_storage_driver_descriptors,
        crate::api::routes::admin::policies::create_policy,
        crate::api::routes::admin::policies::get_policy,
        crate::api::routes::admin::policies::get_policy_capacity,
        crate::api::routes::admin::policies::update_policy,
        crate::api::routes::admin::policies::delete_policy,
        crate::api::routes::admin::policies::test_policy_connection,
        crate::api::routes::admin::policies::promote_s3_compatible_policy_driver,
        crate::api::routes::admin::policies::test_policy_params,
        crate::api::routes::admin::policies::execute_saved_storage_policy_action,
        crate::api::routes::admin::policies::execute_draft_storage_policy_action,
        crate::api::routes::admin::policies::list_storage_credential_providers,
        crate::api::routes::admin::policies::start_storage_authorization,
        crate::api::routes::admin::policies::finish_storage_authorization,
        crate::api::routes::admin::policies::list_storage_policy_credentials,
        crate::api::routes::admin::policies::validate_storage_policy_credential,
        crate::api::routes::admin::policies::list_policy_groups,
        crate::api::routes::admin::policies::create_policy_group,
        crate::api::routes::admin::policies::get_policy_group,
        crate::api::routes::admin::policies::update_policy_group,
        crate::api::routes::admin::policies::delete_policy_group,
        crate::api::routes::admin::policies::migrate_policy_group_assignments,
        crate::api::routes::admin::storage_migrations::create_storage_policy_migration,
        crate::api::routes::admin::storage_migrations::dry_run_storage_policy_migration,
        crate::api::routes::admin::storage_migrations::resume_storage_policy_migration,
        crate::api::routes::admin::remote_nodes::list_remote_nodes,
        crate::api::routes::admin::remote_nodes::create_remote_node,
        crate::api::routes::admin::remote_nodes::get_remote_node,
        crate::api::routes::admin::remote_nodes::update_remote_node,
        crate::api::routes::admin::remote_nodes::delete_remote_node,
        crate::api::routes::admin::remote_nodes::test_remote_node,
        crate::api::routes::admin::remote_nodes::test_remote_node_params,
        crate::api::routes::admin::remote_nodes::create_remote_node_enrollment_token,
        crate::api::routes::admin::remote_nodes::list_remote_node_ingress_profiles,
        crate::api::routes::admin::remote_nodes::create_remote_node_ingress_profile,
        crate::api::routes::admin::remote_nodes::update_remote_node_ingress_profile,
        crate::api::routes::admin::remote_nodes::delete_remote_node_ingress_profile,
        crate::api::routes::admin::external_auth::list_external_auth_provider_kinds,
        crate::api::routes::admin::external_auth::list_external_auth_providers,
        crate::api::routes::admin::external_auth::create_external_auth_provider,
        crate::api::routes::admin::external_auth::get_external_auth_provider,
        crate::api::routes::admin::external_auth::update_external_auth_provider,
        crate::api::routes::admin::external_auth::delete_external_auth_provider,
        crate::api::routes::admin::external_auth::test_external_auth_provider_params,
        crate::api::routes::admin::external_auth::test_external_auth_provider,

        // admin::users：后台用户列表、资料维护、会话回收和强制删除。
        crate::api::routes::admin::users::list_users,
        crate::api::routes::admin::users::create_user,
        crate::api::routes::admin::users::list_user_invitations,
        crate::api::routes::admin::users::create_user_invitation,
        crate::api::routes::admin::users::revoke_user_invitation,
        crate::api::routes::admin::users::get_user,
        crate::api::routes::admin::users::update_user,
        crate::api::routes::admin::users::reset_user_password,
        crate::api::routes::admin::users::reset_user_mfa,
        crate::api::routes::admin::users::revoke_user_sessions,
        crate::api::routes::admin::users::get_user_avatar,
        crate::api::routes::admin::users::force_delete_user,

        // admin::teams：后台视角的团队管理、成员维护和审计日志查询。
        crate::api::routes::admin::teams::list_teams,
        crate::api::routes::admin::teams::create_team,
        crate::api::routes::admin::teams::get_team,
        crate::api::routes::admin::teams::update_team,
        crate::api::routes::admin::teams::delete_team,
        crate::api::routes::admin::teams::restore_team,
        crate::api::routes::admin::teams::list_team_audit_logs,
        crate::api::routes::admin::teams::list_team_members,
        crate::api::routes::admin::teams::add_team_member,
        crate::api::routes::admin::teams::patch_team_member,
        crate::api::routes::admin::teams::delete_team_member,

        // admin::config：系统配置、模板变量和可执行配置动作的管理接口。
        crate::api::routes::admin::config::list_config,
        crate::api::routes::admin::config::get_config,
        crate::api::routes::admin::config::set_config,
        crate::api::routes::admin::config::delete_config,
        crate::api::routes::admin::config::execute_config_action,
        crate::api::routes::admin::config::config_schema,
        crate::api::routes::admin::config::config_template_variables,

        // admin::shares：后台对全站分享的审查和强制删除能力。
        crate::api::routes::admin::shares::list_all_shares,
        crate::api::routes::admin::shares::admin_delete_share,

        // admin::files：后台文件与 blob 可观测查询。
        crate::api::routes::admin::files::list_files,
        crate::api::routes::admin::files::get_file,
        crate::api::routes::admin::files::list_file_blobs,
        crate::api::routes::admin::files::get_file_blob,

        // admin::tasks：后台任务列表查询与条件清理。
        crate::api::routes::admin::tasks::list_tasks,
        crate::api::routes::admin::tasks::cleanup_tasks,

        // admin::locks：后台锁列表、强制解锁和过期锁清理。
        crate::api::routes::admin::locks::list_locks,
        crate::api::routes::admin::locks::force_unlock,
        crate::api::routes::admin::locks::cleanup_expired_locks,

        // admin::audit_logs：全站审计日志查询。
        crate::api::routes::admin::audit_logs::list_audit_logs,

        // share_public：匿名访问公开分享时使用的浏览、下载、鉴权和缩略图接口。
        crate::api::routes::share_public::get_share_info,
        crate::api::routes::share_public::verify_password,
        crate::api::routes::share_public::archive_preview,
        crate::api::routes::share_public::create_preview_link,
        crate::api::routes::share_public::download_shared,
        crate::api::routes::share_public::create_stream_session,
        crate::api::routes::share_public::stream_shared_video,
        crate::api::routes::share_public::create_folder_file_preview_link,
        crate::api::routes::share_public::folder_file_archive_preview,
        crate::api::routes::share_public::download_shared_folder_file_handler,
        crate::api::routes::share_public::create_folder_file_stream_session,
        crate::api::routes::share_public::list_shared_content,
        crate::api::routes::share_public::list_shared_subfolder_content,
        crate::api::routes::share_public::shared_avatar,
        crate::api::routes::share_public::shared_thumbnail,
        crate::api::routes::share_public::shared_image_preview,
        crate::api::routes::share_public::shared_media_metadata,
        crate::api::routes::share_public::shared_folder_file_thumbnail,
        crate::api::routes::share_public::shared_folder_file_image_preview,
        crate::api::routes::share_public::shared_folder_file_media_metadata,

        // wopi：给 Office/WOPI 集成方回调使用的文件元数据读取接口。
        crate::api::routes::wopi::check_file_info,
    ),
    components(
        schemas(
            // api::api_error_code / api::pagination / api::response：统一错误码、分页结构和通用响应模型。
            crate::api::api_error_code::ApiErrorCode,
            crate::api::pagination::SortBy,
            crate::api::pagination::SortOrder,
            crate::api::pagination::LimitOffsetQuery,
            crate::api::pagination::FolderListQuery,
            crate::api::pagination::TrashListQuery,
            crate::api::pagination::OffsetPage<crate::services::audit_service::AuditLogEntry>,
            crate::api::pagination::OffsetPage<crate::services::audit_service::TeamAuditEntryInfo>,
            crate::api::pagination::OffsetPage<crate::api::dto::admin::AdminFileInfo>,
            crate::api::pagination::OffsetPage<crate::api::dto::admin::AdminFileBlobInfo>,
            crate::api::pagination::OffsetPage<crate::services::user_service::UserInfo>,
            crate::api::pagination::OffsetPage<crate::services::user_invitation_service::AdminUserInvitationInfo>,
            crate::api::pagination::OffsetPage<crate::services::team_service::AdminTeamInfo>,
            crate::api::pagination::OffsetPage<crate::services::policy_service::StoragePolicy>,
            crate::api::pagination::OffsetPage<crate::services::policy_service::StoragePolicyGroupInfo>,
            crate::api::pagination::OffsetPage<crate::services::managed_follower_service::RemoteNodeInfo>,
            crate::api::pagination::OffsetPage<crate::services::share_service::ShareInfo>,
            crate::api::pagination::OffsetPage<crate::services::share_service::MyShareInfo>,
            crate::api::pagination::OffsetPage<crate::services::task_service::types::TaskInfo>,
            crate::api::pagination::OffsetPage<crate::services::config_service::SystemConfig>,
            crate::api::pagination::OffsetPage<crate::services::lock_service::ResourceLock>,
            crate::api::pagination::OffsetPage<crate::services::webdav_account_service::WebdavAccountInfo>,
            crate::api::pagination::OffsetPage<crate::services::external_auth_service::AdminExternalAuthProviderInfo>,
            crate::api::pagination::OffsetPage<crate::services::tag_service::TagInfo>,
            crate::api::response::ApiEmptyData,
            crate::api::response::ApiErrorDiagnostic,
            crate::api::response::ApiErrorInfo,
            crate::api::response::HealthResponse,
            crate::api::response::MemoryStatsResponse,
            crate::api::response::PurgedCountResponse,
            crate::api::response::RemovedCountResponse,
            crate::api::response::SystemInfoResponse,

            // services::admin_service / services::audit_service / services::task_service：后台概览、审计与后台任务细节模型。
            crate::services::audit_service::AuditLogFilterQuery,
            crate::services::audit_service::AuditLogEntry,
            crate::services::audit_service::AuditPresentation,
            crate::services::audit_service::AuditPresentationMessage,
            crate::services::audit_service::TeamAuditEntryInfo,
            crate::services::admin_service::AdminOverviewQuery,
            crate::services::admin_service::AdminOverview,
            crate::services::admin_service::AdminOverviewStats,
            crate::services::admin_service::AdminOverviewDailyReport,
            crate::services::task_service::types::ArchiveCompressTaskPayload,
            crate::services::task_service::types::ArchiveExtractTaskPayload,
            crate::services::task_service::types::ArchivePreviewTaskPayload,
            crate::services::task_service::types::ArchiveCompressTaskResult,
            crate::services::task_service::types::ArchiveExtractTaskResult,
            crate::services::task_service::types::ArchivePreviewTaskResult,
            crate::services::task_service::types::TaskPayload,
            crate::services::task_service::types::TaskResult,
            crate::services::task_service::types::TaskInfo,
            crate::services::task_service::types::TaskPresentation,
            crate::services::task_service::types::TaskPresentationCode,
            crate::services::task_service::types::TaskPresentationMessage,
            crate::services::task_service::types::TaskStepInfo,
            crate::services::task_service::types::TaskStepStatus,
            crate::types::BackgroundTaskKind,
            crate::types::BackgroundTaskStatus,
            crate::types::AuditAction,
            crate::types::ArchiveFilenameEncoding,
            crate::services::archive_preview_service::ArchivePreviewManifest,
            crate::services::archive_preview_service::ArchivePreviewEntry,
            crate::services::archive_preview_service::ArchivePreviewEntryKind,
            crate::services::archive_preview_service::ArchivePreviewExtractCompatibility,
            crate::services::archive_preview_service::ArchivePreviewExtractUnsupportedReason,

            // services::folder_service / entities::{file,folder,file_version}：个人空间文件树、文件实体和版本信息模型。
            crate::services::folder_service::FolderContents,
            crate::services::folder_service::FolderAncestorItem,
            crate::services::workspace_models::FileInfo,
            crate::services::workspace_models::FolderInfo,
            crate::entities::file::Model,
            crate::entities::folder::Model,
            crate::entities::file_version::Model,
            crate::api::routes::files::FileQuery,
            crate::api::routes::files::PatchFileReq,
            crate::api::routes::files::OpenWopiRequest,
            crate::api::dto::admin::AdminFileListQuery,
            crate::api::dto::admin::AdminFileBlobListQuery,
            crate::api::dto::admin::AdminFileInfo,
            crate::api::dto::admin::AdminFileDetail,
            crate::api::dto::admin::AdminFileBlobSummary,
            crate::api::dto::admin::AdminFileVersionSummary,
            crate::api::dto::admin::AdminFileBlobHashKind,
            crate::api::dto::admin::AdminFileBlobInfo,
            crate::api::dto::admin::AdminFileBlobDetail,
            crate::api::dto::admin::AdminFileBlobReferenceFile,
            crate::api::dto::admin::AdminFileBlobReferenceVersion,
            crate::api::routes::folders::CreateFolderReq,
            crate::api::routes::folders::PatchFolderReq,
            crate::api::routes::folders::SetLockReq,
            crate::api::routes::files::SetLockReq,
            crate::api::routes::files::CopyFileReq,
            crate::api::routes::folders::CopyFolderReq,
            crate::services::direct_link_service::DirectLinkTokenInfo,
            crate::services::preview_link_service::PreviewLinkInfo,
            crate::services::stream_ticket_service::StreamTicketInfo,
            crate::services::wopi_service::WopiLaunchSession,
            crate::services::media_metadata_service::MediaMetadataInfo,
            crate::types::MediaMetadataKind,
            crate::types::MediaMetadataStatus,
            crate::types::ImageMediaMetadata,
            crate::types::AudioMediaMetadata,
            crate::types::VideoMediaMetadata,
            crate::types::MediaMetadataPayload,

            // api::routes::auth / services::{user_service,profile_service} / types：认证、用户资料与偏好设置模型。
            crate::api::routes::auth::CheckResp,
            crate::api::routes::auth::SetupReq,
            crate::api::routes::auth::RegisterReq,
            crate::api::routes::auth::AcceptUserInvitationReq,
            crate::api::routes::auth::ResendRegisterActivationReq,
            crate::api::routes::auth::ContactVerificationConfirmQuery,
            crate::api::routes::auth::LoginReq,
            crate::api::routes::auth::AuthTokenResp,
            crate::api::routes::auth::LoginResponse,
            crate::api::routes::auth::MeQuery,
            crate::api::routes::auth::ActionMessageResp,
            crate::api::routes::auth::PasswordResetRequestReq,
            crate::api::routes::auth::PasswordResetConfirmReq,
            crate::services::user_service::UserCore,
            crate::services::user_service::UserInfo,
            crate::services::user_invitation_service::AdminUserInvitationInfo,
            crate::services::user_invitation_service::PublicUserInvitationInfo,
            crate::services::user_service::MeResponse,
            crate::services::user_service::MePartialResponse,
            crate::services::storage_change_service::StorageChangeEvent,
            crate::services::storage_change_service::StorageChangeKind,
            crate::services::storage_change_service::StorageChangeWorkspace,
            crate::types::UserRole,
            crate::types::UserStatus,
            crate::types::UserInvitationStatus,
            crate::types::AvatarSource,
            crate::types::VerificationPurpose,
            crate::types::ThemeMode,
            crate::types::ColorPreset,
            crate::types::PrefViewMode,
            crate::types::BrowserOpenMode,
            crate::types::Language,
            crate::services::user_service::UserPreferences,
            crate::services::user_service::UpdatePreferencesReq,
            crate::services::profile_service::AvatarInfo,
            crate::services::profile_service::UserProfileInfo,
            crate::api::routes::auth::ChangePasswordReq,
            crate::api::routes::auth::RequestEmailChangeReq,
            crate::api::routes::auth::UpdateProfileReq,
            crate::api::routes::auth::UpdateAvatarSourceReq,
            crate::services::auth_service::AuthSessionInfo,
            crate::services::external_auth_service::ExternalAuthPublicProvider,
            crate::services::external_auth_service::ExternalAuthStartLoginRequest,
            crate::services::external_auth_service::ExternalAuthStartLoginResponse,
            crate::services::external_auth_service::ExternalAuthCallbackQuery,
            crate::services::external_auth_service::ExternalAuthLinkInfo,
            crate::services::external_auth_service::AdminExternalAuthProviderInfo,
            crate::services::external_auth_service::CreateExternalAuthProviderInput,
            crate::services::external_auth_service::UpdateExternalAuthProviderInput,
            crate::services::external_auth_service::ExternalAuthProviderTestResult,
            crate::services::external_auth_service::ExternalAuthEmailVerificationStartRequest,
            crate::services::external_auth_service::ExternalAuthPasswordLinkRequest,
            crate::services::external_auth_service::ExternalAuthEmailVerificationStartResponse,
            crate::services::external_auth_service::ExternalAuthEmailVerificationConfirmQuery,
            crate::services::storage_credential_service::StorageCredentialProviderInfo,
            crate::services::storage_credential_service::StorageAuthorizationStartResponse,
            crate::services::storage_credential_service::StorageAuthorizationCallbackQuery,
            crate::services::storage_credential_service::StorageAuthorizationCallbackOutcome,
            crate::services::storage_credential_service::StoragePolicyCredentialInfo,
            crate::services::storage_credential_service::StoragePolicyCredentialValidationResult,
            crate::services::storage_credential_service::MicrosoftGraphAuthorizationInput,
            crate::storage::MicrosoftGraphApplicationConfigInput,
            crate::storage::StorageConnectorApplicationConfigInput,
            crate::services::storage_credential_service::MicrosoftGraphAuthorizationContext,
            crate::types::ExternalAuthProviderOptions,
            crate::types::MicrosoftExternalAuthProviderOptions,
            crate::types::ExternalAuthProviderKind,
            crate::types::ExternalAuthProtocol,
            crate::services::mfa_service::MfaChallengeVerifyRequest,
            crate::services::mfa_service::MfaChallengeVerifyResponse,
            crate::services::mfa_service::MfaEmailCodeSendRequest,
            crate::services::mfa_service::MfaEmailCodeSendResponse,
            crate::services::mfa_service::MfaStatus,
            crate::services::mfa_service::MfaFactorInfo,
            crate::services::mfa_service::TotpSetupStartResponse,
            crate::services::mfa_service::TotpSetupFinishRequest,
            crate::services::mfa_service::TotpSetupFinishResponse,
            crate::services::mfa_service::MfaSensitiveActionRequest,
            crate::services::mfa_service::MfaChallengeMethod,
            crate::types::MfaMethod,
            crate::types::MfaPersistentFactorMethod,

            // api::routes::admin / services::{config_service,policy_service,preview_app_service} / entities::storage_policy_group：后台配置与存储策略模型。
            crate::entities::storage_policy_group::Model,
            crate::entities::storage_policy_group_item::Model,
            crate::api::routes::admin::CreatePolicyReq,
            crate::api::routes::admin::PatchPolicyReq,
            crate::api::routes::admin::PromoteS3CompatiblePolicyDriverReq,
            crate::api::routes::admin::DeletePolicyQuery,
            crate::api::routes::admin::PolicyGroupItemReq,
            crate::api::routes::admin::CreatePolicyGroupReq,
            crate::api::routes::admin::PatchPolicyGroupReq,
            crate::api::routes::admin::MigratePolicyGroupAssignmentsReq,
            crate::api::routes::admin::CreateUserReq,
            crate::api::routes::admin::CreateUserInvitationReq,
            crate::api::routes::admin::PatchUserReq,
            crate::api::routes::admin::ResetUserPasswordReq,
            crate::api::routes::admin::AdminAuditLogSortQuery,
            crate::api::routes::admin::AdminLockListQuery,
            crate::api::routes::admin::AdminPolicyListQuery,
            crate::api::routes::admin::AdminPolicyGroupListQuery,
            crate::api::routes::admin::AdminRemoteNodeListQuery,
            crate::api::routes::admin::AdminShareListQuery,
            crate::api::routes::admin::AdminTaskListQuery,
            crate::api::routes::admin::AdminTaskCleanupReq,
            crate::api::routes::admin::AdminTeamListQuery,
            crate::api::routes::admin::AdminUserListQuery,
            crate::api::routes::admin::AdminCreateTeamReq,
            crate::api::routes::admin::AdminPatchTeamReq,
            crate::api::routes::admin::TestPolicyParamsReq,
            crate::api::routes::admin::ExecuteSavedStoragePolicyActionReq,
            crate::api::routes::admin::ExecuteDraftStoragePolicyActionReq,
            crate::api::routes::admin::CreateRemoteNodeReq,
            crate::api::routes::admin::PatchRemoteNodeReq,
            crate::api::routes::admin::TestRemoteNodeParamsReq,
            crate::api::routes::admin::SetConfigReq,
            crate::api::routes::admin::ExecuteConfigActionReq,
            crate::api::routes::admin::ExecuteConfigActionResp,
            crate::services::config_service::SystemConfig,
            crate::services::config_service::ConfigSchemaItem,
            crate::services::config_service::ConfigSchemaOption,
            crate::services::config_service::TemplateVariableItem,
            crate::services::config_service::TemplateVariableGroup,
            crate::services::config_service::ConfigActionType,
            crate::services::config_service::PublicBranding,
            crate::services::config_service::PublicFrontendConfig,
            crate::services::config_service::PublicFrontendMediaConfig,
            crate::config::media_processing::PublicExtensionSupport,
            crate::config::media_processing::PublicImagePreviewPreference,
            crate::config::media_processing::PublicMediaDataKindSupport,
            crate::config::media_processing::PublicMediaDataKindsSupport,
            crate::config::media_processing::PublicMediaDataSupport,
            crate::config::media_processing::PublicMediaDataSupportMatch,
            crate::config::media_processing::PublicThumbnailSupport,
            crate::services::preview_app_service::PreviewAppProvider,
            crate::services::preview_app_service::PreviewOpenMode,
            crate::services::preview_app_service::PublicPreviewAppConfig,
            crate::services::preview_app_service::PublicPreviewAppDefinition,
            crate::services::preview_app_service::PublicPreviewAppsConfig,
            crate::services::policy_service::StoragePolicy,
            crate::services::policy_service::StoragePolicyActionResult,
            crate::services::policy_service::StoragePolicyDiagnostic,
            crate::services::policy_service::TencentCosCorsConfigResult,
            crate::services::policy_service::StoragePolicyGroupItemInfo,
            crate::services::policy_service::StoragePolicyGroupInfo,
            crate::services::policy_service::StoragePolicyGroupItemInput,
            crate::services::policy_service::PolicyGroupAssignmentMigrationResult,
            crate::services::managed_follower_service::RemoteNodeInfo,
            crate::storage::remote_protocol::RemoteIngressProfileInfo,
            crate::storage::remote_protocol::RemoteCreateIngressProfileRequest,
            crate::storage::remote_protocol::RemoteUpdateIngressProfileRequest,
            crate::storage::remote_protocol::RemoteStorageCapabilities,
            crate::types::DriverType,
            crate::types::ObjectStorageDownloadStrategy,
            crate::types::ObjectStorageUploadStrategy,
            crate::types::RemoteDownloadStrategy,
            crate::types::StoragePolicyOptions,
            crate::types::SystemConfigSource,
            crate::types::SystemConfigValueType,

            // api::routes::shares / api::routes::share_public / services::{share_service,lock_service}：分享、公开访问和锁持有者模型。
            crate::services::share_service::ShareInfo,
            crate::services::share_service::ShareTarget,
            crate::services::share_service::MyShareInfo,
            crate::services::share_service::ShareStatus,
            crate::services::share_service::SharePublicOwnerInfo,
            crate::services::share_service::SharePublicInfo,
            crate::services::share_stream_service::ShareStreamSessionInfo,
            crate::services::lock_service::WopiLockOwnerInfo,
            crate::services::lock_service::WebdavLockOwnerInfo,
            crate::services::lock_service::TextLockOwnerInfo,
            crate::services::lock_service::ResourceLockOwnerInfo,
            crate::services::lock_service::ResourceLock,
            crate::api::routes::shares::CreateShareReq,
            crate::api::routes::shares::UpdateShareReq,
            crate::api::routes::shares::BatchDeleteSharesReq,
            crate::api::dto::DirectLinkQuery,
            crate::api::routes::share_public::VerifyPasswordReq,

            // api::routes::files / services::{upload_service,webdav_account_service} / entities::upload_session：上传流程与 WebDAV 账户模型。
            crate::api::routes::files::InitUploadReq,
            crate::api::routes::files::CompleteUploadReq,
            crate::api::routes::files::CompletedPartReq,
            crate::api::routes::files::PresignPartsReq,
            crate::entities::upload_session::Model,
            crate::services::upload_service::InitUploadResponse,
            crate::services::upload_service::ChunkUploadResponse,
            crate::services::upload_service::UploadProgressResponse,
            crate::services::webdav_account_service::WebdavAccount,
            crate::services::webdav_account_service::WebdavAccountCreated,
            crate::services::webdav_account_service::WebdavAccountInfo,
            crate::api::dto::WopiAccessQuery,
            crate::api::dto::WebdavSettingsInfo,
            crate::api::dto::CreateWebdavAccountReq,
            crate::api::dto::TestConnectionReq,

            // services::trash_service / api::routes::trash：回收站浏览、还原与清理模型。
            crate::services::trash_service::TrashContents,
            crate::services::trash_service::TrashFileItem,
            crate::services::trash_service::TrashFolderItem,
            crate::api::dto::TrashItemPath,

            // services::team_service / api::routes::teams / entities::{team,team_member}：团队、成员与团队分页模型。
            crate::entities::team::Model,
            crate::entities::team_member::Model,
            crate::services::team_service::AdminTeamInfo,
            crate::services::team_service::TeamInfo,
            crate::services::team_service::TeamMemberInfo,
            crate::services::team_service::TeamMemberPage,
            crate::api::routes::teams::ListTeamsQuery,
            crate::api::routes::teams::CreateTeamReq,
            crate::api::routes::teams::PatchTeamReq,
            crate::api::routes::teams::AddTeamMemberReq,
            crate::api::routes::teams::PatchTeamMemberReq,
            crate::api::routes::teams::ListTeamMembersQuery,
            crate::types::TeamMemberRole,

            // services::property_service / api::routes::properties：实体属性的读写模型。
            crate::services::property_service::EntityProperty,
            crate::api::dto::SetPropReq,

            // services::tag_service / api::routes::tags：文件/文件夹标签定义、摘要和绑定请求模型。
            crate::services::tag_service::TagInfo,
            crate::services::tag_service::TagSummary,
            crate::services::tag_service::EntityTags,
            crate::api::dto::CreateTagReq,
            crate::api::dto::PatchTagReq,
            crate::api::dto::ReplaceEntityTagsReq,
            crate::api::dto::BatchTagBindingReq,

            // db::repository::search_repo / services::search_service：搜索条件、结果项和聚合返回模型。
            crate::db::repository::search_repo::FileSearchItem,
            crate::services::search_service::SearchParams,
            crate::services::search_service::SearchResults,

            // api::routes::batch / services::batch_service：批量操作和归档下载请求/结果模型。
            crate::api::routes::batch::ArchiveDownloadReq,
            crate::api::routes::batch::BatchDeleteReq,
            crate::api::routes::batch::BatchMoveReq,
            crate::api::routes::batch::BatchCopyReq,
            crate::services::batch_service::BatchResult,
            crate::services::batch_service::BatchItemError,
        ),
    ),
    tags(
        (name = "auth", description = "Authentication"),
        (name = "files", description = "File operations"),
        (name = "folders", description = "Folder operations"),
        (name = "admin", description = "Admin operations"),
        (name = "shares", description = "File/folder sharing"),
        (name = "trash", description = "Recycle bin"),
        (name = "teams", description = "Team and membership management"),
        (name = "webdav", description = "WebDAV account management"),
        (name = "properties", description = "Entity properties"),
        (name = "tags", description = "File and folder tags"),
        (name = "health", description = "Health checks"),
        (name = "search", description = "Search files and folders"),
        (name = "batch", description = "Batch operations"),
        (name = "public", description = "Anonymous public endpoints"),
    ),
)]
pub struct ApiDoc;

/// 注册 Cookie + Bearer 两种认证方式到 OpenAPI security schemes
struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi.components.get_or_insert_with(Default::default);
        // "bearer" 匹配 utoipa actix_extras 从 JwtAuth 中间件自动推断的 scheme 名
        components.add_security_scheme(
            "bearer",
            SecurityScheme::Http(Http::new(HttpAuthScheme::Bearer)),
        );
        components.add_security_scheme(
            "cookie_auth",
            SecurityScheme::ApiKey(ApiKey::Cookie(ApiKeyValue::new("aster_access"))),
        );
    }
}
